[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
PORT = "3001"
NODE_ENV = "production"
